---
apiVersion: v1
kind: Namespace
metadata:
  name: <APPSUB-NS>
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: <APPSUB_NAME>
  namespace: <APPSUB-NS>
  labels:
    app: <APPSUB-NAME>
spec:
  channel: ns-ch/predev-ch
  name: nginx-ingress
  packageFilter:
    version: "1.36.x"
  placement:
    placementRef:
      kind: PlacementRule
      name: towhichcluster
