# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# Copyright (c) 2020 Red Hat, Inc

{{- if .Values.subscriptionrelease.enabled }}
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "subscription-release.fullname" . }}
  labels:
    app: {{ template "subscription-release.name" . }}
    chart: {{ template "subscription-release.chart" . }}
    component: "application-manager-subscription-release"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    connectionManager: {{ .Values.connectionManager }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ template "subscription-release.name" . }}
      component: "application-manager-subscription-release"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "subscription-release.name" . }}
        component: "application-manager-subscription-release"
        controller: "operator"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        chart: {{ template "subscription-release.chart" . }}
      annotations:
        productName: "IBM Multicloud Manager - Klusterlet"
        productID: "c18240a57c1c41969d5e81b39435da6c"
        productVersion: "3.2.1"
    spec:
      hostAliases:
      - hostnames:
        - {{ .Values.subscriptionrelease.hostname }}
        ip: {{ .Values.subscriptionrelease.ip }}
      serviceAccountName: {{ template "subscription-release.fullname" . }}
      containers:
      - name: subscription-release-controller
        image: "{{ .Values.subscriptionrelease.image.repository }}:{{ .Values.subscriptionrelease.image.tag }}"
        imagePullPolicy: "{{ .Values.subscriptionrelease.image.pullPolicy }}"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          procMount: Default
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        command:
        - multicloud-operators-subscription-release
        env:
        - name: CHARTS_DIR
          value: "/charts"
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "multicloud-operators-subscription-release"
        volumeMounts:
        - name: charts
          mountPath: "/charts"
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
      volumes:
        - name: charts
          emptyDir: {}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.imagePullSecret }}"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
