apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "application-manager.fullname" . }}-predelete"
  labels:
    component: "application-manager"
    "open-cluster-management.io/addon-pre-delete": ""
spec:
  template:
    metadata:
      name: "{{ template "application-manager.fullname" . }}-predelete"
      labels:
        component: "application-manager"
    spec:
      restartPolicy: Never
      serviceAccountName: {{ template "application-manager.fullname" . }}
      containers:
      - name: pre-delete-job
        image: "{{ .Values.global.imageOverrides.multicluster_operators_subscription }}"
        imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
        command: ["uninstall-crd"]
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.global.imagePullSecret }}"
      {{- end }}
