apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ansible
  namespace: ansible-pre-post
spec:
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - ansible
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
